### ISSUE TITLE
Add node API vocabulary endpoints and logic to send requests to specified APIs

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/federation-api#12]
As the query tool, talking to the federation-API should be the same as talking to a node-API. The only difference is that from a federation-API I get a potentially longer list of answers from. 

Therefore
- endpoints and query parameters should be called the same as in https://github.com/neurobagel/api
- response shemas on these endpoints should be the same

**Comment by rmanaem** [comment]
For clarification, does implementation of this issue include the three endpoints under the `attributes` path?

**Comment by surchs** [comment]
I would say, given the focus on the query tool here, we could start with the `attributes/{data_element}/vocab` endpoint because that's what the query tool really relies on. So you could split off the other two `attributes` endpoints into their own issues that we address later. @alyssadai ?

**Comment by alyssadai** [comment]
Sorry for the late reply @rmanaem. I think `attributes/{data_element_URI}` is most important, since this is what returns all the instances of a variable in the graph (@surchs, I think this is what you meant too?).

That said, I think we probably also want to include `attributes/{data_element}/vocab`, because this is what actually will give the mappings of term IDs to human-readable labels, which is what the query tool needs to display to the user. So the order of operations from the query tool would be:

1. Get all term _IDs_ existing in a graph for a given variable using `attributes/{data_element_URI}`
2. Get the term _labels_ to populate the dropdown UIs from `attributes/{data_element}/vocab`

If adding `attributes/{data_element}/vocab` seems too big for this issue however, I'm okay to split it off.

**Comment by rmanaem** [comment]
> I would say, given the focus on the query tool here, we could start with the attributes/{data_element}/vocab endpoint because that's what the query tool really relies on. 

I think that'd be the `attributes/{data_element_URI}` since we want to display the available options from graph.

**Comment by surchs** [comment]
ah, yes, I think you are right, I mixed up the endpoints. What I meant was: let's do the endpoint first that gives us the available **instances** of terms inside the graph

**Comment by rmanaem** [comment]
Blocked by https://github.com/neurobagel/api/issues/217

**Comment by alyssadai** [comment]
Unblocked now that https://github.com/neurobagel/api/issues/217 is merged

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/federation-api/releases/tag/v0.1.0) :rocket:
