### ISSUE TITLE
Have tests run in CI

### ISSUE THREAD

**Issue by surchs** [neurobagel/federation-api#15]
We have (some) tests, let's have them run so we feel good. And then let's add more tests as part of PRs that touch the code base

**Comment by alyssadai** [comment]
https://github.com/neurobagel/federation-api/tree/main/tests 👀

Would definitely benefit from a test workflow too though 😅

**Comment by surchs** [comment]
Oh wow, how did I miss that? I was looking for them after I saw that we had no runners on the last PR. Ok, let's tone down that issue title maybe ...

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/federation-api/releases/tag/v0.1.0) :rocket:
