### ISSUE TITLE
Add query parameter for node URLs

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/federation-api#27]
- [x] New parameter should be a list (https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values-with-defaults)
- [x] Default value if parameter not provided should be all the nodes the API knows about
- [x] If node URL provided that is not recognized/known by the federation API instance, throw an informative HTTPException
- [x] Any empty string `""` URLs in the list should be ignored
- [x] Duplicates should be removed

**Comment by alyssadai** [comment]
Blocked by #28 to properly populate and parse default values

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/federation-api/releases/tag/v0.1.0) :rocket:
