### ISSUE TITLE
Use logger for printing info to console

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/federation-api#53]
- This will replace all existing warnings and print statements
- Tests also need to be updated

Replace

- `print` with `logging.info`
- `warning` with `logging.warning`

Keep
- `exception` but add `logging.exception`: https://docs.python.org/3/library/logging.html#logging.Logger.exception

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/federation-api/releases/tag/v0.1.0) :rocket:
